fix: get cached keystoneauth session instead of from neutron
Fix  bug in bootstrap_default_hub: `tunelo_project_id = get_neutron_session().get_project_id()`
raised `AttributeError: 'Client' object has no attribute 'session'`

Instead move the neutron session to a dedicated global var, and get it, and the client separately.